### ISSUE TITLE
ایرانسل

### ISSUE THREAD

**Issue by mojvan** [IranITDefenders/irans-closed-bankrupt-companies#5]
[//]: # (اسم شرکت را در پایین وارد کنید)
# ایرانسل

## توضیحات
[//]: # (توضیحات را بجای <توضیحات> وارد کنید)
ضرر چندصد میلیاردی

## اطلاعات
[//]: # (اطلاعات ایمیل، وبسایت، صفحه مجازی، سال تعطیلی و .... را بجای <اطلاعات> وارد کنید)
[//]: # (میتوانید اطلاعات را به صورت bullet point اضافه کنید)
- irancell.ir

**Comment by mehdi-ra** [comment]
#8
