### ISSUE TITLE
شاتل

### ISSUE THREAD

**Issue by mojvan** [IranITDefenders/irans-closed-bankrupt-companies#7]
[//]: # (اسم شرکت را در پایین وارد کنید)
# شاتل

## توضیحات
[//]: # (توضیحات را بجای <توضیحات> وارد کنید)
ضرر چند میلیاردی

## اطلاعات
[//]: # (اطلاعات ایمیل، وبسایت، صفحه مجازی، سال تعطیلی و .... را بجای <اطلاعات> وارد کنید)
[//]: # (میتوانید اطلاعات را به صورت bullet point اضافه کنید)
- shattel.ir

**Comment by mojvan** [comment]
freedom for Iran

**Comment by mehdi-ra** [comment]
همینطور که در این ایشو توضیح دادم #8
