### ISSUE TITLE
مبین نت

### ISSUE THREAD

**Issue by mojvan** [IranITDefenders/irans-closed-bankrupt-companies#8]
[//]: # (اسم شرکت را در پایین وارد کنید)
# مبین نت

## توضیحات
[//]: # (توضیحات را بجای <توضیحات> وارد کنید)
ضرر چند میلیاردی

**Comment by mehdi-ra** [comment]
سلام، ممنون از همکاری اما لطفا شرکت هایی که میدوند بسته شدند یا بسته میشوند رو اضافه کنید.
